version: '3.8'

services:
  db:
    container_name: db
    image: postgres:15-alpine
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    user: postgres

  back:
    container_name: back
    build: ../backend/
    restart: always
    volumes:
      - static_volume:/app/hackathon_projects/static/
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    container_name: nginx
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx-local.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/var/html/static/
    depends_on:
      - back

volumes:
  static_volume:
  db_data: