HASHED_ID_MAX_LEN: int = 32
CITY_TITLE_MAX_LEN: int = 150
DIVISION_TITLE_MAX_LEN: int = 150
STORE_TITLE_MAX_LEN: int = 150
FORMAT_TITLE_MAX_LEN: int = 150
LOC_TYPE_MAX_LEN: int = 255
SIZE_TYPE_MAX_LEN: int = 150
