# Generated by Django 4.2.5 on 2023-10-06 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.CharField(
                        db_index=True,
                        help_text="Хэшированный ID",
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория товара",
                "verbose_name_plural": "Категории товаров",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.CharField(
                        db_index=True,
                        help_text="Хэшированный ID",
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Группа товара",
                "verbose_name_plural": "Группы товаров",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="UOM",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        db_index=True,
                        help_text="ID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Наименование",
                        max_length=150,
                        verbose_name="Наименование",
                    ),
                ),
            ],
            options={
                "verbose_name": "Маркер товара",
                "verbose_name_plural": "Маркеры товаров",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="Subcategory",
            fields=[
                (
                    "id",
                    models.CharField(
                        db_index=True,
                        help_text="Хэшированный ID",
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category_id",
                    models.ForeignKey(
                        help_text="ID категории товара",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="subcategory",
                        to="products.category",
                        verbose_name="Категория товара",
                    ),
                ),
            ],
            options={
                "verbose_name": "Подкатегория товара",
                "verbose_name_plural": "Подкатегории товаров",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="StockKeepingUnit",
            fields=[
                (
                    "id",
                    models.CharField(
                        db_index=True,
                        help_text="Хэшированный ID",
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Наименование",
                        max_length=150,
                        null=True,
                        verbose_name="Наименование",
                    ),
                ),
                (
                    "cat_id",
                    models.ForeignKey(
                        help_text="ID категории товара",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="products",
                        to="products.category",
                        verbose_name="Категория товара",
                    ),
                ),
                (
                    "group_id",
                    models.ForeignKey(
                        help_text="ID группы товара",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="products",
                        to="products.group",
                        verbose_name="Группа товара",
                    ),
                ),
                (
                    "subcat_id",
                    models.ForeignKey(
                        help_text="ID подкатегории товара",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="products",
                        to="products.subcategory",
                        verbose_name="Подкатегория товара",
                    ),
                ),
                (
                    "uom_id",
                    models.ForeignKey(
                        help_text="ID маркера товара (вес/шт)",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="products",
                        to="products.uom",
                        verbose_name="Вес/шт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
                "ordering": ("id",),
            },
        ),
        migrations.AddField(
            model_name="category",
            name="group_id",
            field=models.ForeignKey(
                help_text="ID группы категории товара",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="category",
                to="products.group",
                verbose_name="Группа категории товара",
            ),
        ),
    ]
