# Generated by Django 4.2.5 on 2023-10-06 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.CharField(
                        db_index=True,
                        help_text="Хэшированный ID",
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        verbose_name="Название города",
                    ),
                ),
            ],
            options={
                "verbose_name": "Город",
                "verbose_name_plural": "Города",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="Division",
            fields=[
                (
                    "id",
                    models.CharField(
                        db_index=True,
                        help_text="Хэшированный ID",
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        verbose_name="Название подразделения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Подразделение",
                "verbose_name_plural": "Подразделения",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="Format",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=150, verbose_name="Формат супермаркета"
                    ),
                ),
            ],
            options={
                "verbose_name": "Формат супермаркетов",
                "verbose_name_plural": "Форматы супермаркетов",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        max_length=255, verbose_name="Тип локации/окружения"
                    ),
                ),
            ],
            options={
                "verbose_name": "Тип локации/окружения",
                "verbose_name_plural": "Типы локации/окружения",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="Size",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        max_length=150, verbose_name="Тип размера"
                    ),
                ),
            ],
            options={
                "verbose_name": "Размер супермаркетов",
                "verbose_name_plural": "Размеры супермаркетов",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.CharField(
                        db_index=True,
                        help_text="Хэшированный ID",
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        verbose_name="Название супермаркета",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Флаг активного магазина"
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="stores",
                        to="stores.city",
                        verbose_name="Город",
                    ),
                ),
                (
                    "division",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="stores",
                        to="stores.division",
                        verbose_name="Подразделение",
                    ),
                ),
                (
                    "loc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="stores",
                        to="stores.location",
                        verbose_name="Местоположение",
                    ),
                ),
                (
                    "size",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="stores",
                        to="stores.size",
                        verbose_name="Размер",
                    ),
                ),
                (
                    "type_format",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="stores",
                        to="stores.format",
                        verbose_name="Формат магазина",
                    ),
                ),
            ],
            options={
                "verbose_name": "Супермаркет",
                "verbose_name_plural": "Супермаркеты",
                "ordering": ("id",),
            },
        ),
    ]
