# Generated by Django 4.2.5 on 2023-10-06 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("stores", "0001_initial"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Forecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "forecast_date",
                    models.DateField(help_text="Дата", verbose_name="Дата"),
                ),
                (
                    "sku",
                    models.ForeignKey(
                        help_text="Товар",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="forecasts",
                        to="products.stockkeepingunit",
                        verbose_name="Товар",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        help_text="Супермаркет",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="forecasts",
                        to="stores.store",
                        verbose_name="Супермаркет",
                    ),
                ),
            ],
            options={
                "verbose_name": "Прогноз",
                "verbose_name_plural": "Прогнозы",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="ForecastData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField(default=dict)),
                (
                    "forecast_id",
                    models.ForeignKey(
                        help_text="ID прогноза",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="forecasts.forecast",
                        verbose_name="ID прогноза",
                    ),
                ),
            ],
            options={
                "verbose_name": "Данные прогноза",
                "verbose_name_plural": "Данные прогнозов",
                "ordering": ("id",),
            },
        ),
    ]
