# Generated by Django 4.2.5 on 2023-10-06 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='forecastdata',
            table='forecastdata',
        ),
    ]
